language: cpp
dist: bionic
matrix:
    include:
        - os: linux
          compiler: gcc

        - os: osx
          osx_image: xcode9.3
          compiler: gcc
script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE="Release" ..
    - make -j8


